prompts = {
    "behavior_control": '''### Instruction
You are a psychological counseling expert. You will be provided with an incomplete conversation between an Assistant and a User. 
Please analyze whether this conversation reflects the user's current emotional state, the reason the user is seeking emotional support, and how the user plans to cope with the event. 
If all three points are reflected, please reply "YES," otherwise reply "NO." 

### Conversation
{context}

Your answer must include two parts:
1. "YES" or "NO"
2. If "YES", briefly explain how the conversation reflects these elements; if "NO", explain which elements are missing.

Your answer must follow this format:
1. [YES or NO]
2. [explaination]
''',

    "zero_shot": '''### Instruction
You are a psychological counseling expert. You will be provided with a dialogue context between an 'Assistant' and a 'User'. Your task is to play a role as 'Assistant' and generate a response based on the given dialogue context. 

### Dialogue context
{context}

Respond to the user's latest turn with a natural, context-specific sentence.
Avoid broad reassurance that could fit any conversation.
Use a concrete detail from the dialogue when one is available.
Your answer must be fewer than 30 words and must follow this format:
Response: [response]
''',

    "get_joint_analysis": '''### Instruction
You are a psychological counseling expert. You will be provided with a dialogue context between an 'Assistant' and a 'User'.

Please analyze the user's last utterance and jointly infer:
1. the emotional state expressed by the user
2. the specific event that led to the user's emotional state
3. the user's intention for addressing that event

Keep the three analyses mutually consistent. Ground every field in the dialogue context and avoid inventing unnecessary details.

### Dialogue context
{context}

Your answer must follow this format:
Emotion: [emotion]
Emotion Reasoning: [reasoning]
Event: [event]
Event Reasoning: [reasoning]
Intention: [intention]
Intention Reasoning: [reasoning]
''',

    "select_strategy_mixture_panel": '''### Instruction
You are selecting {agent_num} compact strategy-mixture candidates for an emotional-support response.
You will be given the dialogue context, the user's inferred emotional state, event, intention, and similar strategy-response examples.

### Candidate selection instructions
{expert_perspectives}

### Dialogue context
{context}

### Emotional state
{emo_and_reason}

### Event
{cau_and_reason}

### Intention
{int_and_reason}

### Similar examples
{examples}

For each candidate, choose up to {max_strategies} strategies that should guide one final Assistant response.
Use only one primary strategy unless a secondary strategy is truly needed.
Secondary strategies must support the primary strategy; do not create a scattered or overly broad response.
Every selected strategy must appear in the similar examples.
Keep each candidate meaningfully distinct in response act and wording while staying grounded in the dialogue.
Do not assign fixed roles such as empathy-first, exploration-first, or advice-first.

Your answer must follow this format exactly:
Expert 1:
Primary Strategy: [strategy]
Secondary Strategies: {secondary_format}
Mixing Plan: [brief plan]

Expert 2:
Primary Strategy: [strategy]
Secondary Strategies: {secondary_format}
Mixing Plan: [brief plan]

Expert 3:
Primary Strategy: [strategy]
Secondary Strategies: {secondary_format}
Mixing Plan: [brief plan]
''',

    "response_with_strategy_mixture": '''### Instruction
You are a psychological counseling expert. Generate one concise Assistant response using the selected strategy mixture.

### Dialogue context
{context}

### Emotional state
{emo_and_reason}

### Event
{cau_and_reason}

### Intention
{int_and_reason}

### Strategy mixture
{strategy_mixture}

### Similar examples
{top_examples}

Use the primary strategy as the main response style.
Use secondary strategies only if they naturally improve the response.
Do not mention strategy names in the response.
Do not copy the similar examples verbatim.
Avoid generic counseling templates such as broad reassurance without a detail from the user's situation.
Use concrete details from the dialogue when they are available.
Vary the wording naturally; do not rely on stock openings like "It sounds really tough" unless that is the most precise wording.
Your answer must be fewer than 30 words and must follow this format:
Response: [response]
''',

    "refine_with_strategy_mixture": '''### Instruction
You are a reflective response refiner for emotional-support dialogue.
You will be given the dialogue context, top-k similar reference examples, and multiple candidate responses generated by different strategy-mixture agents.

### Dialogue context
{context}

### Emotional state
{emo_and_reason}

### Event
{cau_and_reason}

### Intention
{int_and_reason}

### Default strategy mixture
{strategy_mixture}

### Default draft response
{draft_response}

### Top-k similar reference examples
{top_examples}

### Compared candidate responses
{candidate_responses}

First select exactly one candidate as the primary base response.
Then make a minimal edit only if needed.

Default behavior:
- If the selected candidate is already natural, coherent, and context-specific, return it unchanged.
- Do not rewrite just to make the wording more polished.

If an edit is needed, refine that selected candidate so that it:
- follows the selected candidate's primary strategy
- preserves the selected candidate's main wording, concrete details, and response act
- keeps at least two meaningful content words or short phrases from the selected candidate when possible
- naturally incorporates secondary strategies only if they clearly improve the response
- matches the helpfulness and tone pattern of the reference examples without copying them verbatim
- does not introduce unsupported advice
- borrows at most one small useful element from another candidate
- does not mechanically merge all candidates
- does not replace specific wording with generic reassurance
- avoids stock counseling openings unless they are clearly grounded in the dialogue
- stays under 30 words

Your answer must follow this format:
Selected Candidate: [candidate id]
Response: [response]
'''
}

def get_prompt(prompt_name):
    if prompt_name not in prompts:
        raise ValueError(f"Prompt '{prompt_name}' not found.")
    return prompts[prompt_name]
